#!/usr/bin/env osascript
tell application "Finder" to set frontmost to true
tell application "System Events" to keystroke "v" using {option down, command down}
tell application "Finder" to set frontmost to false
