#!/bin/zsh
osascript - "$@" <<EOF
set thePath to "$@" as text
set name_ to name of (info for thePath)
set a_ to count thePath
set b_ to count name_
set minus_ to a_ - b_
set parentPath to text 1 thru (minus_) of thePath
tell application "Finder" to set target of front Finder window to (POSIX file parentPath)
tell application "Finder" to reveal thePath as POSIX file
EOF
