#!/bin/zsh
VALID_MIMETYPES=(
  "image/jpeg"
  "image/png"
  "image/tiff"
  "image/webp"
  "image/gif"
  "image/psd"
  "audio/ogg"
  "audio/flac"
  "audio/x-aiff"
  "audio/x-m4a"
  "audio/mpeg"
  "video/mov"
  "video/mp4"
  "video/mpg"
  "video/mpeg"
  "video/mpeg2"
  "video/MP2T"
  "video/3gpp"
  "video/3gpp2"
  "video/h261"
  "video/h263"
  "video/h264"
  "video/h265"
  "video/webm"
  "video/jpeg"
  "video/x-m4v"
  "video/x-msvideo"
  "video/x-matroska"
  "video/quicktime"
  "video/ogg"
  "application/x-mpegURL"
  "application/mxf"
  "video/x-ms-wmv"
)

containsElement () {
  local e
  for e in "${@:2}"; do [[ "$e" == "$1" ]] && return 0; done
  return 1
}

FILE_MIME=$(file -b --mime-type "$1")
if containsElement "$FILE_MIME" "${VALID_MIMETYPES[@]}"
  then
    if [[ $1 == --exit ]]; then
        mpv-close-front
    else
        open --background -a /Applications/mpv.app "$1"
    fi
fi
